[Unit]
RequiresMountsFor=/data

[Service]
Environment=MKV_CONFIG=/etc/mkvtools/config.ssd.yaml
ExecStartPre=/usr/bin/install -d -o root -g root -m 0755 /data/inbox /data/work /data/done /data/downloads
